baseurl = "https://geekx.tech/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "blog"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

[languages]
  [languages.en]
    title = "Sagar Ladla"
    subtitle = ""
    keywords = ""
    copyright = "Sagar Ladla"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Sagar Ladla"
      logoHomeLink = "https://geekx.tech/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
      [[languages.en.menu.main]]
        identifier = "email"
        name = "Email"
        url = "mailto:help@geekx.tech"
      [[languages.en.menu.main]]
        identifier = "search"
        name = "Search"
        url = "/search"
